// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/guild-wars2-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"achievement | authenticated | daily_reward | game_mechanic | guild | guild_authenticated | home_instance | item | map | map_information | miscellaneous | story | structured_pv_p | trading_post | world_vs_world"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.GuildWars2SDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "guild-wars2_list",
		Description: "List records from GuildWars2. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "guild-wars2_load",
		Description: "Load a single record from GuildWars2. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.GuildWars2SDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.GuildWars2SDK, name string) (sdk.GuildWars2Entity, error) {
	switch strings.ToLower(name) {
	case "achievement":
		return client.Achievement(nil), nil
	case "authenticated":
		return client.Authenticated(nil), nil
	case "daily_reward":
		return client.DailyReward(nil), nil
	case "game_mechanic":
		return client.GameMechanic(nil), nil
	case "guild":
		return client.Guild(nil), nil
	case "guild_authenticated":
		return client.GuildAuthenticated(nil), nil
	case "home_instance":
		return client.HomeInstance(nil), nil
	case "item":
		return client.Item(nil), nil
	case "map":
		return client.Map(nil), nil
	case "map_information":
		return client.MapInformation(nil), nil
	case "miscellaneous":
		return client.Miscellaneous(nil), nil
	case "story":
		return client.Story(nil), nil
	case "structured_pv_p":
		return client.StructuredPvP(nil), nil
	case "trading_post":
		return client.TradingPost(nil), nil
	case "world_vs_world":
		return client.WorldVsWorld(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
